<?php
$I = new AcceptanceTester($scenario);
$I->amOnPage('/');
$I->wantTo('perform actions and see result');
$I->click('.header-sign__reg._action');
$I->fillField('input[id="email"]', 'lkml@mail.ru');
$I->fillField('#pass', 'qwerty123');
$I->click('.auth_button.js-submitBtn');
$I->amOnPage('/');
$I->see('.header-sign__login');
$I->click('.header-sign__login');
$I->see('.login-nav');
$I->click('.header-login__addjob-btn _action');
$I->see('.b-modal__window', 'Подать работу на участие');
$I->click('.b-popup-addwork__select addwork-category__select_cont');
$I->click('.addwork-contest__select');
$I->click('.b-popup-addwork__radio');
$I->fillField('input[id="name_work"]', 'Сладость-радость');
$I->seeInField('textarea[name="work[name]"]','Сладость-радость');
$I->fillField('input[id="adv_prod"]', 'Шоколад Спартак');
$I->seeInField('textarea[name="work[name]"]','Шоколад Спартак');
$I->click('.typecompany__radio _radio-yes');
$I->fillField('#agency', 'Diva');
$I->seeInField('textarea[name="work[company_name]"]','Diva');
$I->fillField('#customer', 'СП ОАО "Спартак"');
$I->seeInField('textarea[name="work[customer]"]','СП ОАО "Спартак"');
$I->fillField('#idea', 'Разнообразие вкусов белорусского шоколада');
$I->seeInField('textarea[name="work[idea]"]','Разнообразие вкусов белорусского шоколада');
$I->click('.workseries__radio _radio-yes');
$I->fillField('#name_series', 'Мир шоколада');
$I->seeInField('textarea[name="name_series"]','Мир шоколада');
$I->click('.b-popup-addwork__input-file _action-file-input');
$I->see('b-popup-addwork__btn-load-file _action-load', 'Загрузить работу');
$I->fillField('#video', 'https://www.youtube.com/watch?v=AMIHp1UY6r4');
$I->seeInField('textarea[name="work[video_link]"]','https://www.youtube.com/watch?v=AMIHp1UY6r4');
$I->fillField('#www', 'http://spartak.by/');
$I->seeInField('textarea[name="work[site]"]','http://spartak.by/');
$I->click('.b-popup-addwork__submit js-submitBtn');
$I->dontSeeElement('.b-modal__window');
$I->see('Работа добавлена', 'header');
?>
